### PR TITLE
Add environment.yml to ease conda usage

### PR DESCRIPTION
**Pull request by ctrueden**
Using conda, launching ImagePy from source can now be done like this:

```
conda env create
conda activate imagepy
python -m imagepy
```

### CODE REVIEW

**Comment by constantinpape** [comment]
@ctrueden the first line should probably be
```
conda env create -f /path/to/environment.yml
```

**Comment by ctrueden** [comment]
@constantinpape The `-f environment.yml` is implied if you are in a folder with one present.

**Comment by ctrueden** [comment]
I also tested it on a fresh Ubuntu Linux 18.04 LTS system, and it worked great. (There was one warning about a particular plugin/feature only supported on Windows and macOS, but I think it is not relevant here.)

**Comment by yxdragon** [comment]
merged but I would remove the opencv dependence. If the launch log has a bed experience, I can remove the cv demo plugin too.

**Comment by ctrueden** [comment]
Thanks! My suggestion would be to move the opencv demo plugin to its own repo, so that the dependency can be declared correctly.

**Pull request merged**
